# Generated by Django 4.2.3 on 2024-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0002_alter_userreg_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userimg'),
        ),
    ]
