# Generated by Django 4.2.3 on 2024-08-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0003_userreg_gender_userreg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
