# Generated by Django 4.2.1 on 2024-09-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0006_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userimg'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userimg'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
