# Generated by Django 4.2.1 on 2024-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0007_coordinator_email_coordinator_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=30, null=True),
        ),
    ]
