# Generated by Django 5.1.4 on 2025-01-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0009_hotel_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('current_occupancy', models.PositiveIntegerField()),
                ('orphanage_type', models.CharField(choices=[('GENERAL', 'General Orphanage'), ('INFANT', 'Infant Orphanage'), ('SPECIAL_NEEDS', 'Special Needs Orphanage'), ('COMMUNITY', 'Community Orphanage'), ('SINGLE_PARENTS', 'Single Parent Orphanage'), ('FOSTER', 'Foster Care Home'), ('ADOPTION', 'Adoption Home'), ('SCHOOL', 'Orphanage with Schooling'), ('REFUGEE', 'Refugee Orphanage'), ('CULTURAL', 'Cultural Orphanage'), ('EMERGENCY', 'Emergency Shelter Orphanage')], default='GENERAL', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='orphanage_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='hotel',
        ),
    ]
