# Generated by Django 5.1.4 on 2025-01-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0010_orphanage_delete_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage',
            name='password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
