# Generated by Django 5.1.4 on 2025-01-06 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0012_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_details', models.TextField()),
                ('quantity', models.PositiveIntegerField(help_text='Number of meals')),
                ('proposed_pickup_time', models.DateTimeField()),
                ('proposed_location', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COLLECTED', 'Collected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharebite.hotel')),
            ],
        ),
    ]
