# Generated by Django 5.1.4 on 2025-01-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0013_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Coordinator handling this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharebite.coordinator'),
        ),
        migrations.AddField(
            model_name='donation',
            name='orphanage',
            field=models.ForeignKey(blank=True, help_text='Orphanage assigned to this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharebite.orphanage'),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REQUESTED', 'Requested by Orphanage'), ('APPROVED', 'Approved by Admin'), ('COLLECTED', 'Collected by Coordinator'), ('RECEIVED', 'Received by Orphanage')], default='PENDING', max_length=20),
        ),
    ]
