# Generated by Django 5.1.4 on 2025-03-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharebite', '0015_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userreg',
        ),
    ]
